# Generated by Django 6.0 on 2025-12-17 05:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "account_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("account_name", models.CharField(max_length=100)),
                ("app_secret_token", models.CharField(max_length=255, unique=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
